### ISSUE TITLE
Installing DKAN with composer failes

### ISSUE THREAD

**Issue by simonovskifilip** [GetDKAN/dkan#3391] opened 2021-03-07 19:16 UTC
I was reading the [docs](https://demo.getdkan.org/modules/contrib/dkan/docs/start.html) for DKAN2 and tryed to install it by running:  
`composer require 'getdkan/dkan'` and `composer require getdkan/dkan:2.9.1` 
This gives the following error message:  
```
Problem 1
    - Root composer.json requires getdkan/dkan 2.9.0 -> satisfiable by getdkan/dkan[2.9.0].
    - getdkan/dkan 2.9.0 requires drupal/admin_toolbar ^2.3 -> could not be found in any version, there may be a typo in the package name.
```

**Comment by JeffersonWood** [comment] 2022-01-11 00:48
Any solution to this? Just tried to install using composer on our development site, but failed because admin_toolbar was locked to version ^3.0

**Comment by paul-m** [comment] 2024-02-01 23:21
Duplicate of #3402

Read there for a solution.

**Closed as completed by paul-m** 2024-02-01 23:21 UTC
