### ISSUE TITLE
Discovery: can datastore be stored externally to DKAN?

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2529] opened 2018-05-22 00:39 UTC
Stub ticket: what would an MVP for an externally-stored, detachable datastore look like? 

What work would need to take place?
What other issues would this cause?
Would this simplify or complicate known issues?
Are there performance pros and cons?

**Comment by erogray** [comment] 2018-05-22 00:40
For @fmizzell to contemplate when he has leisure time. @grugnog and @acouch may also have valuable input.

**Comment by dafeder** [comment] 2018-10-30 15:16
Duplicate of #2571

**Closed by dafeder** 2018-10-30 15:16 UTC
