### ISSUE TITLE
Printing React Dashboards

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2118] opened 2017-09-15 17:00 UTC
Connects https://github.com/GetDKAN/dkan/issues/2475

Can we replace the high overhead code of creating dashboard PDF files with improved print styles

- Figure out how much we need a PDF, why can't we just print the page? 
  -- Kim to ask clients in check ins today
  -- This would likely take a little bit of training, since people rarely think to print pages
- We can do some work to make the dashboard look better when the page is printed (we can even add a print button) Likely 2-ish days of work.
- Any work to make the pages look better for individual customers would be custom.
- We would also need to remove the current PDF button
- The ability to print dashboard pages nicely would also solve the problem of printing filtered dashboards.

**Comment by kimwdavidson** [comment] 2017-09-21 18:21
Notes from meeting here: https://civicactions.slack.com/files/U0CNZ1R36/F6Z5XDG81/PDF_discussion_notes

**Comment by alexiscott** [comment] 2017-09-27 08:28
This ticket can be closed once the sub tickets have been completed.

**Comment by kimwdavidson** [comment] 2017-09-29 20:54
@alexiscott Can I close this as a duplicate of the new tickets?

**Comment by alexiscott** [comment] 2017-10-04 13:33
<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Page</th>
<th scope="col" class="org-left">Issue/s</th>
<th scope="col" class="org-left">Repo (if known)</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">[Physician workforce data](https://gbpw.georgia.gov/physician-workforce-data)</td>
<td class="org-left">Images cut off for printing</td>
<td class="org-left">DKAN</td>
</tr>


<tr>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">[Main Publications Reports](https://gbpw.georgia.gov/main-publications-reports)</td>
<td class="org-left">Not all graphs showing in print dialogue</td>
<td class="org-left">ga<sub>reports</sub></td>
</tr>


<tr>
<td class="org-left">&#xa0;</td>
<td class="org-left">Remove PDF links when ready.</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">All pages</td>
<td class="org-left">Search box should not show on print</td>
<td class="org-left">DKAN</td>
</tr>


<tr>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>
</tbody>
</table>

**Comment by alexiscott** [comment] 2017-10-04 13:36
@kimwdavidson I wonder if this ticket makes sense as a place in which we could maintain a list of links of all the URLs affected, which a brief one liner about what the issue is?

**Comment by acouch** [comment] 2018-06-27 15:05
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.

**Closed by acouch** 2018-06-27 15:05 UTC
Labels: Needs spec
