### ISSUE TITLE
Discovery: Search and narrowing down unique identifiers

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#2755] opened 2018-11-26 17:15 UTC
As a Site Manager, I want to find all datasets with an identifier of AAA-001-ZZZ.

This is a unique identifier assigned to specific datasets under the "Identifier" field. For associated datasets, it is listed under "IsPartOf."

If I search for "AAA-001-ZZZ" with hyphens, nothing comes up.

If I search for it without hyphens, I'm able to pull up all AAA-001-ZZZ associated datasets. However, I cannot narrow it down to whether it's listed as the Identifier or the IsPartOf field.

Additionally, after searching for AAA-001-ZZZ without hyphens, other datasets sometimes appear in search -- without it being listed in either the Identifier or IsPartOf fields!

**More on discovery:**

This may have to do with search behavior, not necessarily the code itself. We should discuss how one searches, how indexing takes place, what's going on with Project Open Data fields, etc. Maybe worth examining problematic datasets via the site's data.JSON?

**Comment by stefaniefgray** [comment] 2018-11-26 17:16
Original ticket: https://civicactions.atlassian.net/projects/OPENDATA/queues/custom/23/OPENDATA-442

**Comment by dafeder** [comment] 2018-12-05 16:55
Getting more information on how to reproduce this.

**Comment by stefaniefgray** [comment] 2018-12-12 17:17
QA'd this on every DKAN client site + my Jenkins demo

Here are the results: https://docs.google.com/spreadsheets/d/1JFFA5xsiT2p9pJ3DoYJtlXvkOOu3kO8CwZZNt-3HHDU/edit?usp=sharing

This is happening on every site except for HHS and my Jenkins demo. What makes Search on these sites different from other sites?

All tests performed on the live sites for each client, Wed. 12/12/18

**Comment by erogray** [comment] 2019-02-05 19:01
@stefaniefgray can reassess whether or not anyone is currently needing this

**Comment by stefaniefgray** [comment] 2019-02-05 20:19
JIRA ticket: https://civicactions.atlassian.net/browse/OPENDATA-442

**Comment by erogray** [comment] 2019-02-28 17:18
Closing since search for identifiers with hyphens isn't currently a priority for anyone as far as we know

**Closed by erogray** 2019-02-28 17:18 UTC
Labels: Needs Spec
