### ISSUE TITLE
Discovery: ISO 19115 geospatial data - Metadata source module or ODSM?

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#2872] opened 2019-05-07 00:36 UTC
See https://github.com/GetDKAN/dkan/issues/2871 for more details on the ISO 19115 geospatial metadata standard and why it matters to Marine Scotland (amongst other E.U. clients who will have to follow the same standard.)

Based on the user story outlined in 2871 -- would we be able to use the Metadata Source Module or the Open Data Schema Mapper? Which is the best for geospatial metadata?

**Comment by kimwdavidson** [comment] 2019-05-07 16:51
Duplicate of #2871. Closing

**Closed by kimwdavidson** 2019-05-07 16:51 UTC
