### ISSUE TITLE
Reset chart options when chart selection changes

### ISSUE THREAD

**Issue by ajacinto** [GetDKAN/dkan#1572] opened 2016-11-28 07:43 UTC
When clicking on the legend in this stacked bar chart we made in a test instance on Acquia,
http://adbdkan2kbpjq5ofre.devcloud.acquia-sites.com/visualization/ve_chart/136

The x-axis values would get converted to numbers. (see attached screenshots)
![legend-2](https://cloud.githubusercontent.com/assets/716642/20659889/6ddd8b6e-b581-11e6-8d15-84f6e92198fd.png)
![legend-1](https://cloud.githubusercontent.com/assets/716642/20659888/6ddc12ac-b581-11e6-9468-c594a6d673e3.png)

**Comment by jvitello** [comment] 2016-12-09 15:48
@ajacinto I'm having trouble reproducing this on the current dev version of DKAN. The text is not changed when I adjust the legend.

Do you know what version you are using? It would also help track these issues down if you are able to provide a link to the datafile being used.

**Comment by jvitello** [comment] 2016-12-09 23:41
Sorry, I realized I could get to the file via the chart you posted. I tested your file with the fields demonstrated with the latest dev version and everything seemed to be working as expected.

If you post the version you were using and the browser we can take a closer look, but this seems fixed at least on the next major upgrade of your site.

**Comment by ajacinto** [comment] 2016-12-12 08:55
@jvitello - Thanks! We're using Drupal	7.50 with the Install profile DKAN (dkan-7.x-1.12.11) on Acquia. Let us know if you need more information.

**Comment by jvitello** [comment] 2016-12-13 21:51
I'm not able to reproduce on 1.12.11 :/
I don't think there is much more we can do to investigate. You could try the developer group and see if anyone there has ideas or suggestions:
https://groups.google.com/forum/#!forum/dkan-dev

![screen shot 2016-12-13 at 4 45 04 pm](https://cloud.githubusercontent.com/assets/5174815/21160662/a42a7424-c153-11e6-8d8d-6650e059f76d.png)

**Comment by jvitello** [comment] 2016-12-13 22:04
Strike that! I always seem to figure out the important parts right after I post.

I can reproduce if I choose the multiBarChart, select the 'Stacked' field in the 'Extra' field group, then switch to the multiBarHorizontalChart type. The bars remain stacked, and when I change the legend selections I get the numbers.

In the examples above, I used the multiBarHorizontalChart type, and used the 'Show controls' option to produce the horizontal version.

I'll add the issue to the bug queue. I'd stick with the multiBarChart with a 45 'X Label Rotation' in the mean time. If you play with the margins it looks pretty good.

![screen shot 2016-12-13 at 5 03 08 pm](https://cloud.githubusercontent.com/assets/5174815/21161350/306a6ec4-c156-11e6-9165-6a88cd4e2d9f.png)

**Comment by ajacinto** [comment] 2016-12-14 07:50
@jvitello - Noted. Thanks for looking into this. We'll go with this solution for now.

**Comment by janette** [comment] 2017-07-13 21:37
CIVIC-5132

**Comment by acouch** [comment] 2018-06-27 15:14
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.

**Closed by acouch** 2018-06-27 15:14 UTC
Labels: Component: Visualization, Icebox, bug
