### ISSUE TITLE
Feature Request: CSV Format Parameter on DataStore API

### ISSUE THREAD

**Issue by schnuerle** [GetDKAN/dkan#1947] opened 2017-06-16 18:19 UTC
Would like a 'format' parameter option added to the DataStore API.

http://dkan.readthedocs.io/en/latest/apis/datastore-api.html#parameters

Right now JSON is the only format available.  So you could add "&format=csv" to the query string and get just the 'records' part of the current JSON returned as CSV.

**Comment by kimwdavidson** [comment] 2017-11-10 21:14
Hi @schnuerle! This is a duplicate of an existing ticket #1853, so I'm going to close this one up. Thanks!

**Comment by schnuerle** [comment] 2017-12-13 00:06
Hi @kimwdavidson I believe this is a different request/issue than #1853.  This is about different formats coming out of the API, vs converting uploaded data sets into new formats in its entirety.  I think this issue should be easier to accomplish, and should be re-opened.

**Comment by kimwdavidson** [comment] 2017-12-20 21:53
Hi @schnuerle, wanted to let you know that this would likely be a part of our rebuilding the datastore, which is a medium term roadmap item. If you'd like to work on it sooner as part of the current datastore api and contribute that code, we'd be happy to review and merge it as well. Thanks!

**Comment by schnuerle** [comment] 2019-02-21 15:53
Now that the datastore has been rebuilt and separated, is this on the short term roadmap?

**Comment by susisiman** [comment] 2020-09-08 15:23
This will be implemented in DKAN v2. Closed due to inactivity. Feel free to open!

**Closed by susisiman** 2020-09-08 15:23 UTC
Labels: Component: Datastore, Icebox, enhancement
