### ISSUE TITLE
Cannot link RDF files in non RDF/XML serializations

### ISSUE THREAD

**Issue by jakubklimek** [GetDKAN/dkan#1190] opened 2016-06-15 08:41 UTC
There is a limited list of possible file extensions in URLs. For RDF data, I can see the RDF/XML extension .rdf, but there are other serializations which are not supported. (TriG .trig, Turtle .ttl, N-Triples .nt, Nquads .nq, JSON-LD .jsonld)

![image](https://cloud.githubusercontent.com/assets/718827/16073200/1cf45116-32e5-11e6-9081-77a45126c589.png)

I don't see the reason for not allowing arbitrary URL to be here. Instead of limiting the URL format, a mime type should be used to determine whether to process the file or not.

Encountered in the current https://github.com/nucivic/dkan-drops-7 version.

related to #739

**Comment by dafeder** [comment] 2016-08-10 22:32
@jakubklimek we will be brining this improvement into DKAN for the next release. Closing as this is essentially a duplicate of #739

**Comment by dafeder** [comment] 2016-10-05 15:20
@jakubklimek a number of improvements to resource creation and viewing will be included in DKAN 1.13, which I believe will address the issues you raise here. See NuCivic/dkan_dataset#276 to track progress.

**Comment by dafeder** [comment] 2017-11-01 21:05
@jakubklimek I think this is a "won't do" - those are just the built-in formats we support in DKAN, and any additional presentations of the data or metadata can be included as additional "resources" (aka "distributions") on the dataset. Please feel free to re-open or find us on Slack to discuss further.

**Closed by dafeder** 2017-11-01 21:05 UTC

**Comment by jakubklimek** [comment] 2017-11-02 18:51
@dafeder I don't understand what you mean by "can be included". The issue is that I cannot add e.g. a Turtle ".ttl" or JSON-LD ".jsonld" file as a resource/distribution because I cannot link to it the same way I can to an RDF/XML ".rdf" file unless something changed regarding this.
