### ISSUE TITLE
Error when editing menu items

### ISSUE THREAD

**Issue by ergonlogic** [GetDKAN/dkan#812] opened 2015-12-09 03:26 UTC
## Description

There appears to be a bug in the (Entity)Reference Field Synchronization module. It crops up when saving menu items. It throws the following error:

```
Notice: Undefined property: stdClass::$original in ref_field_sync_entity_update() ...
```
## Steps to Reproduce

Editing a menu item (admin/structure/menu/item/MLID) will result in the following issue: https://www.drupal.org/node/2631436

Note that we're translating the menu items as well, enabling locale.module, etc. may be required in order to replicate the issue.
## Acceptance Criteria

The module in question appears semi-abandoned. So, applying the patch I uploaded to the issue referenced above in dkan's makefile should resolve the issue cleanly.

**Comment by janette** [comment] 2016-04-25 19:58
I can not reproduce the issue.

**steps I took:**
drush dl i18n
drush en locale, i18n, i18n_menu
added Spanish language
edited and translated several menu items
no errors

**Comment by janette** [comment] 2016-04-27 14:21
@ergonlogic can you provide more details if you are still experiencing this issue.

**Comment by kimwdavidson** [comment] 2017-10-24 21:00
Cannot reproduce. Closing.

**Closed by kimwdavidson** 2017-10-24 21:00 UTC
Labels: bug
