### ISSUE TITLE
Icon marker-icon.png missing

### ISSUE THREAD

**Issue by horacionomade** [GetDKAN/dkan#2509] opened 2018-05-13 00:11 UTC
## Description

I installed DKAN "dkan-drops-7-master" in a directory of the domain "http://ute-secretariadeeducacion.org/", the directory is called "utedatosabiertos" in such a way that DKAN is working in "https: // ute -secretariadeeducacion.org/utedatosabiertos/ ".
I set the variable "$ base_url = 'https://ute-secretariadeeducacion.org/utedatosabiertos';" so that the paths are assembled correctly.
Up here all good.
Now when you see georeferenced data on a map, the "marker-icon.png" image does not appear.
The code creates the following path: "https://ute-secretariadeeducacion.org/profiles/dkan/libraries/recline/vendor/leaflet/1.0.2/images/marker-icon.png", not knowing that the code is in the "Utedatostos" directory.

## Steps to Reproduce

-Place DKAN in the subdirectory webroot (mine is inside data)
-Update $ base_url in "https://ute-secretariadeeducacion.org/utedatosabiertos"
-Load a CSV with geo-referenced data.
-Activate the "Map" preview and select the fields with the data x - y
-Only appears the legend "Marker Icon" you do not see the image "marker-icon.png"

What is missing me configure?

A thousand thanks for this beautiful tool!

**Comment by dafeder** [comment] 2018-11-06 16:49
Hi @horacionomade - sorry this issue wasn't noticed when you posted it. I'm closing because we haven't ever seen this but please let us know if you were able to fix or if you're still seeing the issue; we can re-open if we're able to reproduce it.

**Closed by dafeder** 2018-11-06 16:49 UTC

**Comment by cvps77** [comment] 2019-01-04 20:12
Hi @horacionomade , did you figure it out how to solve this?, I have the same issue.

Hope you can help me

**Comment by horacionomade** [comment] 2019-01-06 16:48
Hello cvps77 !!!
If I could solve it indirectly:
- Apparently the problem silk xq 'some variable that arms the path that leads to the icon is generated incorrectly. I could not find the code in which this occurs.
-The partial solution that I found is to install DKAN in a subdomain (something that my webhosting allows me), instead of installing it in a directory within the domain. This makes the code generate the path correctly and the icons look perfectly.

I hope it helps you!!

We read!
