### ISSUE TITLE
Admins/editors can't revert new content to previous revisions

### ISSUE THREAD

**Issue by keelahnkhan** [GetDKAN/dkan#793] opened 2015-12-03 18:39 UTC
## Description

Administrators and editors can see and press the Revert button on a particular content (resources, datasets), but they reach an 'access denied' page upon pressing Revert. This seems to be a bug, as administrators have the 'revert content revisions' permission. This was only for new datasets and resources I created manually - the pre-made datasets in dkan didn't have this issue when reverting. [See issue here](https://github.com/NuCivic/pluto/issues/132#issuecomment-161704887) 
## Steps to Reproduce
1. Log in as an admin or editor.
2. Create a new dataset and resource.
3. Edit the dataset or resource. 
4. Press revert for previous revision on the new content's Revision page.

**Comment by kimwdavidson** [comment] 2017-10-24 20:57
Need to determine if this is still an issue.

**Comment by YevheniiPanchenko** [comment] 2018-05-29 10:15
This is still an issue.

**Comment by erogray** [comment] 2019-04-30 17:41
@stefaniefgray can you test?
1. for each standard site role, check reverting per steps above
2. document whether or not behavior is as intended
3. check if one role can revert content created by another role

**Comment by stefaniefgray** [comment] 2019-05-07 20:53
Testing on http://stefanie.dkandemo.nuamsdev.com/users/editor after rebuilding site in Jenkins (7.x-1.x, no parameters):

1. Logged in as an Editor
2. Created new dataset and resource
3. Edited dataset and resource
4. Went to 'Revisions' and tried to revert back to first edition
5. "Access denied - You are not authorized to access this page."

Tried again as admin, and as a Site Manager -- still an issue no matter what. Cannot revert others' content either.

Conclusion: There is a bug preventing users from reverting content back to older versions. There should not be an "Access Denied" page from trying to revert content.

Screenshots:

![Screenshot 2019-05-07 14 53 03](https://user-images.githubusercontent.com/9059428/57332367-dbd59d00-70d7-11e9-93d9-853ef196b146.png)

![Screenshot 2019-05-07 14 51 07](https://user-images.githubusercontent.com/9059428/57332381-e1cb7e00-70d7-11e9-8052-dc309ff94e1a.png)

**Comment by beeyayjay** [comment] 2020-02-12 13:51
Note that if the workbench_moderation module is enabled, the 'Revert' button works properly for editors.

**Comment by beeyayjay** [comment] 2020-02-13 15:37
This turned out to be a bug in the 'Organic groups moderation' module.

**Comment by erogray** [comment] 2020-02-19 17:48
Closing since https://github.com/GetDKAN/dkan/pull/3022 is merged

**Closed by erogray** 2020-02-19 17:48 UTC
Labels: Conversations, bug
