### ISSUE TITLE
Datastore import/drop command improvements

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#3388] opened 2021-03-05 16:00 UTC
* Improve docs and feedback on drop and import commands
* Make import drop first all the time.
* Let the drop and import commands take a distribution or dataset/index in addition to resource ID

**Comment by thierrydallacroce** [comment] 2021-10-13 17:49
I agree these Drush commands need better documentation. I tried dataset uuid, distribution uuid and finally got some result with the resource id (hexadecimal hash of length 32).

`drush dkan:datastore:drop` and `drush dkan:datastore:import` both seem to have issues for me, at least in DKAN 2.11.0.

The following was tried with the "U.S. Tobacco Usage Statistics" dataset. The resource_id was obtained from:
`drush dkan:dataset-info 1f2042ad-c513-4fcf-a933-cae6c6fd35e6`

While `drop` seems to work as advertised, it outputs both a notice and an error:
```
 [notice] Successfully dropped the datastore for 32c9e83b3e42993249f4d785fb4bad6a
 [error]  Error: Call to a member function getUniqueIdentifier() on null in Drupal\datastore\Drush->jobstorePrune() (line 21 of /.../dkan/docroot/modules/contrib/dkan/modules/datastore/src/TableTrait.php)
#1 [internal function]: Drupal\datastore\Drush->drop('32c9e83b3e42993...', Array)
#2 /.../dkan/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#3 /.../dkan/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#4 /.../dkan/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#5 /.../dkan/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(313): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#6 /.../dkan/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /.../dkan/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /.../dkan/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /.../dkan/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /.../dkan/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /.../dkan/vendor/drush/drush/src/Runtime/Runtime.php(48): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /.../dkan/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#13 /.../dkan/vendor/drush/drush/includes/preflight.inc(18): require('/Users/thierry....')
#14 phar:///usr/local/bin/drush/bin/drush.php(143): drush_main()
#15 /usr/local/bin/drush(14): require('phar:///usr/loc...')
#16 {main}. 
```

Importing does not seem to work at all:
`drush dkan:datastore:import 32c9e83b3e42993249f4d785fb4bad6a` displayed no result.
Clearing cache did nothing
Verified no new queue items were waiting for cron.
Preview missing in frontend.

**Comment by dafeder** [comment] 2021-10-13 19:51
Thanks @thierrydallacroce. Will try to reproduce.

**Comment by janette** [comment] 2021-11-10 15:21
duplicate of #3534

**Closed as completed by janette** 2021-11-10 15:21 UTC
