### ISSUE TITLE
When editing, "Save and Add Another" button just saves

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2554] opened 2018-06-09 10:39 UTC
When updating a resource, the "Save and Add another" button seems to do the same thing as the Save button. This works properly when _adding_ a new resource, so maybe it should just be removed from the edit version of the page.

<img width="482" alt="screen shot 2018-06-09 at 6 36 47 am" src="https://user-images.githubusercontent.com/21176376/41190585-db27483c-6baf-11e8-91d4-2c0d3dba7a20.png">

**Comment by dafeder** [comment] 2018-10-30 15:14
Can't reproduce - can you add some more info?

**Comment by eGovCologne** [comment] 2020-02-19 10:36
The problem still occurs with version 1.17.1.

**Comment by dafeder** [comment] 2024-07-03 19:58
DKAN v1 issue, closing due to EOL.

**Closed by dafeder** 2024-07-03 19:58 UTC
Labels: Icebox
