### ISSUE TITLE
dkan Rest APIs

### ISSUE THREAD

**Issue by AhmedKhater** [GetDKAN/dkan#3243] opened 2020-10-24 06:37 UTC
I'm working with DKAN Rest APIs for workflow integrations using the python library pydkan and it's working very well for most of the required functions but there is a function that i don't know how to implement and i hope if you can help me.

I want to attache a remote file to a resource of the dataset, not uploading the file just reference the remote file.

I know how to do this through the admin portal UI but i want to do this by code.

**Comment by rhabbachi** [comment] 2020-10-28 14:18
Duplicate of https://github.com/GetDKAN/dkan/issues/3247

**Closed as completed by rhabbachi** 2020-10-28 14:18 UTC
