### ISSUE TITLE
Require DCO agreement for contributions

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2303] opened 2017-12-29 20:30 UTC
For managing legal risk around contributions. 

- [ ] Marc writes text stating DCO requirement
- [ ] Add text to readme or contrib file
- [ ] Add CLABot (Need to discuss which bot)
- [ ] Marc writes rejection message from bot explaining DCO requirement
- [ ] Update git commit process

**Comment by marctjones** [comment] 2018-01-11 16:41
Should we close #2165 as a duplicate of this issue? @kimwdavidson

**Comment by marctjones** [comment] 2018-01-11 16:45
@fmizzell Not recommending any of these, but here are some Bots I cam across in the course of other conversations:

Department of Defense: https://github.com/deptofdefense/dco-bot

Quote from Owen on slack mentioning two other bots: 

""" Kubernetes (and other Linux Foundation projects) uses a Github bot to check for CLA compliance: https://github.com/clabot/clabot - you can see it in action at https://github.com/kubernetes/charts/pull/351
[3:16 PM] 
I also came across https://github.com/wking/signed-off-by which is an abstraction of the kernel signed-off-by docs for use in other projects"""

**Comment by marctjones** [comment] 2018-01-11 17:36
Unofficial simple website with copy of the latest version of the Linux Developer Certificate of Origin (v1.1). https://developercertificate.org/

Link to official documentation on how to use the DCO as part of submitting a patch to the Linux Kernel: https://www.kernel.org/doc/html/latest/process/submitting-patches.html#developer-s-certificate-of-origin-1-1
Note: The Linux Kernel has a weird process for submitting patches that involves emails that is unique to them. That is not at all required or what I am suggesting we do.

**Comment by susisiman** [comment] 2020-09-08 15:24
We don't have enough contributors that this seems like an issue. Closed due to inactivity. Feel free to open!

**Closed by susisiman** 2020-09-08 15:24 UTC
Labels: Icebox, Project DKAN
