### ISSUE TITLE
Improve datastore API documentation

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#2564] opened 2018-06-14 17:28 UTC
<img width="471" alt="slack" src="https://user-images.githubusercontent.com/314172/41428022-69196dec-6fce-11e8-912e-03d81c4d33b0.png">

**Comment by janette** [comment] 2018-06-14 22:45
Related: https://github.com/GetDKAN/dkan/issues/2488

**Comment by willieseabrook** [comment] 2018-07-10 11:04
This has been noted by our customer. See my more detailed comment in #2488

**Comment by kimwdavidson** [comment] 2018-08-30 15:51
Duplicate of #2488. Closing

**Closed by kimwdavidson** 2018-08-30 15:51 UTC
Labels: Component: Datastore, Component: Datastore API, Needs spec, documentation
