### ISSUE TITLE
Display titles of related materials as links

### ISSUE THREAD

**Issue by ghost** [GetDKAN/dkan#3407] opened 2021-03-19 15:55 UTC
**User story:**
As a data publisher I can specify the link and the title for the link of the dataset related materials so that users can see a user friendly explanation instead of a big URL.
As a site visitor I can see a user friendly explanation of what the dataset related materials are so that I can decide to follow the links or not.

**Acceptance Criteria:**
- When I go to a dataset with related materials
- Then I see the titles of the related materials as links
- And when I click on one
- Then I am taken to the related materials

**Estimate:**
half a day

**Comment by alexiscott** [comment] 2021-04-29 12:30
@cmugisha as i will not be working on the project in May, I think that this will need to be looked at by another dev.

**Comment by dafeder** [comment] 2024-12-16 17:01
Duplicate of #3633

**Closed as not planned** 2024-12-16 17:01 UTC
