### ISSUE TITLE
Cannot link from a resource to a non-existent URL

### ISSUE THREAD

**Issue by jakubklimek** [GetDKAN/dkan#1314] opened 2016-08-11 14:40 UTC
CIVIC-6418

## Description

For some reason, DKAN always dereferences a remote file URL when added as resource, even when the record is added through the Dataset REST API. This means that I am unable to add a resource that points to a non-existent URL. This is highly inconvenient for catalogs which aggregate other catalogs as all records with broken links are lost.

This is related to https://github.com/NuCivic/dkan/issues/739 and https://github.com/NuCivic/dkan/issues/1190
## Steps to Reproduce
1. Create a resource
2. Try to link to a non-existent URL
3. Save the resource
4. The error: `The selected file opendata.cz could not be referenced. Only files with the following extensions are allowed: csv html xls json xlsx doc docx rdf txt jpg png gif tiff pdf odf ods odt tsv geojson xml zip.` is displayed. Note that the explanation is also misleading as the error has nothing to do with file extensions.
## Acceptance Criteria

I would expect DKAN to let me link to non-existent resources. Sure, it will be a broken link, but
1. I would not loose data when importing another catalog with broken links, but including additional resource info
2. It is really unnecessary to resolve every URL, expecially when added in bulk (thousands) through the Dataset REST API. At least make it optional. (Or excuse my ignorance if such a feature is already there)

**Comment by dafeder** [comment] 2017-05-30 14:22
Unfortunately this did not get addressed in 1.13 but we're going to do this soon.

**Comment by dafeder** [comment] 2017-05-30 14:32
The issue is that DKAN makes a file entity object for remote files. It wants to grab the metadata for a file to do this, and if it gets none, it wants to reject the file. So we need to see how easy it is to force DKAN to make a file entity for a non-existant file.

**Comment by jvitello** [comment] 2017-09-05 15:04
We still need to determine a strategy for this, including when datasets are harvested that wouldn't have been allowed to be created on DKAN.

**Comment by dafeder** [comment] 2024-07-03 19:52
DKAN v1 issue, no longer relevant.

**Closed by dafeder** 2024-07-03 19:52 UTC
Labels: Icebox
