### ISSUE TITLE
UTF8 header names in datastore import cause error

### ISSUE THREAD

**Issue by chrodos** [GetDKAN/dkan#2276] opened 2017-12-11 07:04 UTC
Hello,

when i tried to import a csv in the datastore with Greek column titles i got the error SQLSTATE[42000]: Syntax error or access violation: 1166 Incorrect column name ''

When i change the header names to English, the import process completes.

**Comment by kimwdavidson** [comment] 2017-12-20 21:58
Thanks for reporting this, @chrodos. We'll take a look!

**Comment by janette** [comment] 2017-12-21 19:21
@chrodos can you attach the csv file with Greek column titles to this issue

**Comment by chrodos** [comment] 2017-12-23 07:00
@janette Sure. This one gives an error.
[problematic.zip](https://github.com/GetDKAN/dkan/files/1583933/problematic.zip)

**Comment by chrodos** [comment] 2017-12-23 09:51
Now that i give it a better look, It might not be the greek characters the problem, but possible some special characters (e.g., #).

**Comment by chrodos** [comment] 2018-03-17 10:06
Did you manage to replicate the problem?

**Comment by erogray** [comment] 2018-07-24 17:52
@stefaniefgray can you replicate this?

**Comment by kimwdavidson** [comment] 2018-12-12 16:58
@fmizzell: is this ready to re-test?

**Comment by kimwdavidson** [comment] 2018-12-17 16:42
@fmizzell: is this the same issue as #117?

**Comment by jjalcolea** [comment] 2019-04-30 08:17
Hi, I'm experiencing a similar issue with UTF8 spanish characters in data fields.  Please find attached the error and a CSV file to reproduce it.
![error](https://user-images.githubusercontent.com/7276480/56948635-0c926100-6b31-11e9-8e59-73850d823c2c.png)


[test.zip](https://github.com/GetDKAN/dkan/files/3130400/test.zip)

**Comment by erogray** [comment] 2019-05-21 18:00
See also https://github.com/GetDKAN/dkan/issues/117

**Comment by janette** [comment] 2019-05-31 17:14
Also an issue on DKAN2, fails silently.

**Comment by janette** [comment] 2019-05-31 22:16
![valid-chars](https://user-images.githubusercontent.com/314172/58737564-bb8fba00-83c7-11e9-8a84-8581acf3a27a.png)

**Comment by janette** [comment] 2019-06-07 14:10
@chrodos after further testing I think the issue you were running into was having a mysql reserved word/symbol in the header column.

@jjalcolea the file you provided was using the iso-8859-1 encoding, once I converted it to UTF8 it did display the special characters properly.

I will be updating our documentation and closing this issue, let me know if the solutions above do not solve your errors.

**Closed** 2019-06-10 21:30 UTC
Labels: Component: Datastore, Conversations, bug

**Comment by jjalcolea** [comment] 2019-06-19 09:26
@janette, you are right, the issue is solved now (or better: there was no issue). Thanks a lot for looking into this!

Best,

Juanje.
