### ISSUE TITLE
Notice: Undefined index: bundle in FeedsProcessor->bundle() 

### ISSUE THREAD

**Issue by dbourrion** [GetDKAN/dkan#1759] opened 2017-03-02 08:02 UTC
Hi
On a fresh install of dkan, got a lot of 

>  Notice: Undefined index: bundle in FeedsProcessor->bundle() (line 64 of /var/www/html/dkan/profiles/dkan/modules/contrib/feeds/plugins/FeedsProcessor.inc).

**Comment by mohnjatthews** [comment] 2017-04-05 14:41
I too received this error. It showed up when updating DKAN from the previous version.

**Comment by dirdigeng** [comment] 2017-06-17 17:30
I also get this. Seems to be seeking some configuration data that is not (yet?) defined. Occurred after installation of DROPS-7 and after then accepting DKAN updates.

**Comment by janette** [comment] 2017-07-11 19:48
@dirdigeng have you upgraded the feeds module? It is important to stick with the version that ships with the distribution.

**Comment by dafeder** [comment] 2017-11-09 22:29
@dbourrion @dirdigeng we haven't been able to reproduce recently. Closing this issue as at least one of these seems to be due to upgrading a contrib module ahead of DKAN. Feeds in particular needs to be on the version specified in the DKAN makefile. Please re-open or reach out if you're still having issues.

**Closed** 2017-11-09 22:30 UTC

**Comment by oriole9g** [comment] 2017-11-10 10:25
I can confirm that this error appears when you update Feeds module as @dafeder and @janette have said.
