### ISSUE TITLE
Remove iframe previews for Website/API references

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#2297] opened 2017-12-27 15:37 UTC
There are a number of problems with DKAN's current behavior of displaying resources using the "API/Website URL" option. 

* The iFrame as currently implemented is not responsive
* Links can have unpredictable behavior - redirects, URLs that trigger file downloads in one browser and not in another, etc
* Actual API endpoints make no sense to display in an iFrame
* Even when it works, the result often looks "weird" - a busy web page compressed into an iframe inside the DKAN theme can look jarring

We should replace this with a simple catalog page similar to what we see on data.gov and other portals:

https://catalog.data.gov/dataset/fips-county-code-look-up-tool/resource/48245993-8aa1-4ce9-9b6d-ff511eeeec3a

(If/when we implement a link checker, the output could be integrated into the page in a similar way)

Connects GetDKAN/recline#98

**Comment by kimwdavidson** [comment] 2018-01-03 15:16
Duplicate of #2287. Closing

**Closed** 2018-01-03 15:16 UTC
Labels: in progress, USDA
