### ISSUE TITLE
Enable ArcGIS previews for ArcGIS Shapefiles (.shp)

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#2720] opened 2018-10-31 17:49 UTC
As the administrator of a DKAN open portal, I want to be able to upload and share .shp files.

.SHP files are the most common file type exported from ArcGIS, and are therefore one of the most common forms of storing geospatial data.

On admin/dkan/dataset_preview, .SHP files are not given as an option to preview in ArcGIS.

**Acceptance criteria:** .SHP files uploaded to DKAN can be previewed using ArcGIS.

**Comment by akuckartz** [comment] 2018-10-31 18:06
This still is a proprietary ESRI-specific format. And ArcGIS is proprietary software.

**Comment by dafeder** [comment] 2018-11-01 15:17
This is a duplicate of #17

**Closed by dafeder** 2018-11-01 15:17 UTC
