### ISSUE TITLE
Visualizations Entity Is Unable to Read Dates Properly

### ISSUE THREAD

**Issue by hrod** [GetDKAN/dkan#2181] opened 2017-10-13 14:45 UTC
I have a basic graph where the x-axis is supposed to be months with a year (Nov 2014, Dec 2014, etc.) and the y-axis are numbers. However, the x-axis is being converted automatically to numbers:
<img width="757" alt="screen shot 2017-10-13 at 10 42 10 am" src="https://user-images.githubusercontent.com/4369591/31551662-3caaee9c-b003-11e7-85c4-32a862ecf4a0.png">

The data entered is formatted to look like this:

<img width="311" alt="screen shot 2017-10-13 at 10 44 18 am" src="https://user-images.githubusercontent.com/4369591/31551751-83b90f30-b003-11e7-971e-fb3313d16ac7.png">

Is there something I've entered incorrectly, or is this a DKAN bug?

**Comment by janette** [comment] 2017-10-13 21:28
@hrod you can specify the format here
![add_chart___dkan](https://user-images.githubusercontent.com/314172/31567089-62e40a5a-b033-11e7-9cb7-19f4ffdba5fd.png)

And most importantly here: (use a date option not text)
![add_chart___dkan](https://user-images.githubusercontent.com/314172/31567127-91f6848a-b033-11e7-900a-6c99e270b4f4.png)

**Comment by kimwdavidson** [comment] 2017-10-16 20:50
Hi Heather! We're gonna close this, and lemme know if you run into anything else on this front.

Missing you here, but happy to see you... here.
Kim

**Comment by hrod** [comment] 2017-10-26 20:21
Opening back up after conversation with @stefaniefgray . She would like to take a look.

**Comment by stefaniefgray** [comment] 2017-11-02 17:52
This ticket is relevant to: https://waffle.io/GetDKAN/dkan/cards/59a88d3a44580f001cf87335

The CSV that Heather had sent me that did not work as a Visualization: It turns out the file itself is perfectly fine, because it loads properly as a DKAN Data Resource Preview. (Shown as the chart with the yellow line.) 

However, the Visualizations entity refuses to read the Month column as a string -- even when I specify that the field is a string, and set the X-format to "Text."

Therefore, X-field formatting is still buggy.

*Acceptance criteria:* User can use a CSV file to create a Visualization that shows the dates (Mar 14, Apr 14, etc.) properly.

<img width="1220" alt="screen shot 2017-10-31 at 3 41 34 pm" src="https://user-images.githubusercontent.com/9059428/32341854-099de446-bfd5-11e7-8972-f933ec033f98.png">
<img width="2018" alt="screen shot 2017-10-31 at 3 44 26 pm" src="https://user-images.githubusercontent.com/9059428/32341855-09aed652-bfd5-11e7-8fc9-fd586af1cd84.png">
<img width="1474" alt="screen shot 2017-10-31 at 3 44 47 pm" src="https://user-images.githubusercontent.com/9059428/32341856-09c0b6ce-bfd5-11e7-9a80-154ce58749bb.png">

**Comment by janette** [comment] 2017-11-09 05:57
@stefaniefgray can you provide a file that can reproduce this issue.

**Comment by stefaniefgray** [comment] 2017-12-05 19:08
I was able to reproduce the issue thanks to John Quinn at USVA, who was trying to create a visualization from a perfectly normal CSV file with dates in it.

This image shows the original file, as well as what it looks like in DKAN - so it's not an issue with the file:

<img width="1101" alt="screen shot 2017-12-04 at 6 15 01 pm" src="https://user-images.githubusercontent.com/9059428/33625322-30856804-d9c5-11e7-9c23-c3cfde8334de.png">

This is what John Quinn's chart attempt looked like - all of the dates are coming out at 12/31/1969. 

It doesn't even matter if you specify "format: Date" or "X-format: MM/DD/YYYY" - the chart would not say anything other than 12/31/1969.

Here's where I attempted to change the formatting of the CSV with Excel, making sure that it had the exact MM/DD/YYYY format provided by the Viz entity.

<img width="1277" alt="screen shot 2017-12-04 at 6 22 05 pm" src="https://user-images.githubusercontent.com/9059428/33625354-486b0a82-d9c5-11e7-847a-abeff642f654.png">

This still did not work.

More on this bug, in the next comment --

**Comment by stefaniefgray** [comment] 2017-12-05 19:46
Here is a new sample CSV file I created from scratch that shows a brief listing student names and test scores by date:

<img width="430" alt="screen shot 2017-12-05 at 2 26 44 pm" src="https://user-images.githubusercontent.com/9059428/33626394-7356425e-d9c8-11e7-84be-11647588860d.png">

Let's try out this file on each of the different chart types and see which ones are unable to handle dates!

We're going to make the X-field "Test Date" and the Series fields each student name:

<img width="1336" alt="screen shot 2017-12-05 at 2 28 39 pm" src="https://user-images.githubusercontent.com/9059428/33626455-9fe5f5e4-d9c8-11e7-987b-5672e43152b0.png">

Here are the different Chart types to choose from:

<img width="1123" alt="screen shot 2017-12-05 at 2 29 25 pm" src="https://user-images.githubusercontent.com/9059428/33626496-bfd9298e-d9c8-11e7-925c-abe3ba3a226f.png">

First, let's test multi-bar charts:

_**Even when you specify that the X-field should be formatted as a date**_ (see previous screenshot), the Chart will initially load with all dates displayed as lengthy numbers:

<img width="730" alt="screen shot 2017-12-05 at 2 30 36 pm" src="https://user-images.githubusercontent.com/9059428/33626573-006b76be-d9c9-11e7-8eef-cd3642ce812a.png">

Only after selecting "MM/DD/YYYY" as the X-format does the X-axis load as dates:

<img width="1311" alt="screen shot 2017-12-05 at 2 32 00 pm" src="https://user-images.githubusercontent.com/9059428/33626600-17918dd8-d9c9-11e7-862b-c56dfc8a31b3.png">

Switching to a horizontal bar chart (seen above), it works perfectly. Awesome!

Stacked Area Chart just doesn't load, whatsoever:

<img width="1329" alt="screen shot 2017-12-05 at 2 34 09 pm" src="https://user-images.githubusercontent.com/9059428/33626714-6a2daaea-d9c9-11e7-9d4b-f5c6e71f3ae4.png">

None of the other Chart types load, either - which doesn't make much sense, since this could easily be represented with a line or scatter plot.

More in next comment --

**Comment by stefaniefgray** [comment] 2017-12-05 20:57
Let's try something else with dates -- a test file showing earnings by date:

<img width="189" alt="screen shot 2017-12-05 at 2 47 51 pm" src="https://user-images.githubusercontent.com/9059428/33627365-4b1629f0-d9cb-11e7-8a38-db9aa954120c.png">

This works perfectly with all possible Chart types - even the ones that weren't working previously. Hooray!

It looks like Charts is breaking when dates are involved as well as multiple Series fields, not just a single date-to-Series field relationship.

**Comment by acouch** [comment] 2018-06-27 15:27
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.

**Closed by acouch** 2018-06-27 15:27 UTC
Labels: Component: Visualization, Component: Viz Entity, Needs spec, bug
