### ISSUE TITLE
Incorrect dataset count on group page

### ISSUE THREAD

**Issue by vmendieta** [GetDKAN/dkan#2948] opened 2019-08-22 21:42 UTC
incorrect number of dataset per group, all brings 0 dataset, since there are already datasets in those groups

![imagen](https://user-images.githubusercontent.com/8810083/63551774-feaf8400-c503-11e9-99ad-1f02f2d18ebf.png)

for example in the indicated group it shows 0 datasets but in the group node we can see that they have 2
![imagen](https://user-images.githubusercontent.com/8810083/63551853-36b6c700-c504-11e9-80c3-9f8a5fc30209.png)

**Comment by managume** [comment] 2019-08-24 19:20
Did you apply any translation after datasets were created? Or any path modification? I had same issue. 

What happens if you create a new dataset and relate to a group? If continues showing 0 try to recreate a group and assing it the datasets again.

**Comment by erogray** [comment] 2019-10-08 17:54
@stefaniefgray can you investigate?

**Comment by vmendieta** [comment] 2019-10-10 17:29
I may have to see:
Some dataset show the group and others do not, I am using a Spanish translation
![imagen](https://user-images.githubusercontent.com/8810083/66591790-18fff880-eb6a-11e9-8d74-58d38acf491e.png)

![imagen](https://user-images.githubusercontent.com/8810083/66591832-36cd5d80-eb6a-11e9-9818-1bb1d88a9ed9.png)

![imagen](https://user-images.githubusercontent.com/8810083/66591879-52d0ff00-eb6a-11e9-9ad3-44d467bd55d2.png)

**Comment by erogray** [comment] 2019-10-15 18:51
See also https://github.com/GetDKAN/dkan/issues/2970

**Comment by stefaniefgray** [comment] 2019-10-21 21:41
Hi @vmendieta,

Have you tried re-indexing? Please go to `admin/config/search/search_api/index/datasets` to re-index the listing of datasets and their associated groups, and let me know if this solves the issue.

Thanks!
Stefanie Gray
CivicActions Support

**Comment by vmendieta** [comment] 2019-10-22 12:33
there is a function called og_get_entity_groups, in node.inc and og_get_entity_groups in og.module that bring that data .. but or surprise it is only saved in og_membership if it is defined in the Group field in the data set creation form that Values ​​as an organic group mode ... I don't know why being that another type should also be saved. What it was to switch to organic group mode and reload the groups to the dataset one by one ... I don't know if indexing would have worked ... Probably ..

**Comment by janette** [comment] 2019-12-03 18:51
@stefaniefgray have we tried reproducing the issue?

**Comment by beeyayjay** [comment] 2020-02-13 18:50
I haven't been able to reproduce this issue. Translating the site didn't make any difference, either to the count of pre-existing datasets or of new ones. 

I'm wondering about the  Oct 22 comment. Is there another way of attaching datasets to groups besides setting the Group field (og_group_ref) on the dataset?

**Comment by beeyayjay** [comment] 2020-02-14 17:50
Closing because I can't reproduce.

If this is still an issue, feel free to reopen. Include steps to reproduce if possible.

**Closed by beeyayjay** 2020-02-14 17:50 UTC
