### ISSUE TITLE
Recline preview charts (DKAN internal data preview charts) can't display dollar signs

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#1265] opened 2016-07-20 00:57 UTC
My data resource is a listing of destinations of exports from the State of California. Four of the columns contain values in dollar signs:

![screenshot 2016-07-19 17 19 36](https://cloud.githubusercontent.com/assets/9059428/16971565/ec4500f0-4df2-11e6-9d78-47cec8bd715f.png)

The dollar signs look good in the map preview:

![screenshot 2016-07-19 17 19 58](https://cloud.githubusercontent.com/assets/9059428/16971576/02c2c858-4df3-11e6-9c13-f22afa957ce1.png)

Unfortunately, they cause Recline to crash. Recline chart previews cannot handle any data containing the dollar sign character ($):

![screenshot 2016-07-19 17 19 47](https://cloud.githubusercontent.com/assets/9059428/16971643/7c5dcd3e-4df3-11e6-96e9-99de55438cf7.png)

This was a previous shot with the percent sign (%) character; see https://github.com/NuCivic/dkan/issues/426

Maybe the fix was used by @drkloc to fix percent signs would also work for dollar signs.

**Comment by janette** [comment] 2016-11-08 19:36
@stefaniefgray  unable to reproduce on latest build
https://data.montgomerycountymd.gov/api/views/ask7-28ii/rows.csv?accessType=DOWNLOAD

**Comment by stefaniefgray** [comment] 2019-02-08 23:19
Resurrecting this ancient issue because Recline preview charts still can't display dollar signs

Example from 1.16.2, basic CSV:

![screenshot 2019-02-08 16 18 01](https://user-images.githubusercontent.com/9059428/52511446-3e90c880-2bbd-11e9-9ddf-75636293e520.png)

![screenshot 2019-02-08 16 18 30](https://user-images.githubusercontent.com/9059428/52511450-42bce600-2bbd-11e9-8366-c41707044c1d.png)

**Comment by rtnilesh** [comment] 2022-07-13 05:28
can anybody please help how i can install dkan in drupal 9 am facing issue.. please help.

**Comment by dafeder** [comment] 2024-04-10 14:36
Closing 7.x issues, as work on that branch has stopped.

**Closed** 2024-04-10 14:36 UTC
Labels: Component: Recline, bug, Component: File Previews, Icebox
