### ISSUE TITLE
Create new field: “Related materials”

### ISSUE THREAD

**Issue by ghost** [GetDKAN/dkan#3405] opened 2021-03-19 15:54 UTC
## User story:
As a data publisher, when I add a dataset, and I go to the related materials field, then I see the option to add a title and link to additional related materials.

## Acceptance criteria:
Data publishers can see the option to add a title and link to additional related materials.

## Estimate: 
1 hr

**Comment by dafeder** [comment] 2024-12-16 17:01
Duplicate of #3633

**Closed as not planned by dafeder** 2024-12-16 17:01 UTC
