### ISSUE TITLE
Option to delete local file after datastore_importer job completes

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#3344] opened 2021-02-05 20:39 UTC
Datastore import finishes -> emits event
ResourceLocalizer listens, and if config set to “don’t keep local file”, 
* local file is deleted
* filefetcher job record is deleted
* local_file and local_url records are deleted from the resource mapper table

**Comment by dafeder** [comment] 2021-07-12 15:22
Duplicate of #3365

**Closed as completed by dafeder** 2021-07-12 15:22 UTC
