### ISSUE TITLE
X-Value Formats

### ISSUE THREAD

**Issue by ajacinto** [GetDKAN/dkan#1530] opened 2016-11-16 03:27 UTC
Upon adding a chart, the X-format field doesn't appear to work. I'm attaching a screenshot of the values that get rendered on the chart. 

![x-value-formats](https://cloud.githubusercontent.com/assets/716642/20333743/a84f8248-abef-11e6-8cf7-83237e1386a7.jpg)

**Comment by ajacinto** [comment] 2016-11-17 07:35
Here's another version where the x-value format doesn't appear to be influencing the chart. 
![pie-chart-sample](https://cloud.githubusercontent.com/assets/716642/20380173/6bcd6ff0-acdb-11e6-8b15-567bd9ee26d6.jpg)

**Comment by rhabbachi** [comment] 2016-12-07 13:48
Thanks @ajacinto for the bug report! Tracking this issue internally (ticket code CIVIC-5049). We are preparing a new release so looking into this issue can be delayed a bit but it's definitely on our radar now.

**Comment by jvitello** [comment] 2016-12-09 15:32
@ajacinto 

### line charts
Looks like you are adjusting the X-axis formatting when you'll want to change the Y-axis formatting. It's working as expected on the current dev version of DKAN, but not sure which version you are using. I think the reason the X-axis wasn't updating with the format you chose was because it included text ("Q4 "), and there isn't a way to render that as a number.

### pie charts
The pie charts aren't affected by the format changes. The percentages are shown on the chart, and the raw data is displayed on mouseover. It's poor UI to have the additional fields visible when they can't be used, but we haven't gotten far enough along to change the fields based on what kind of chart is selected. This is a back burner improvement at the moment, so I can't really say when this will be addressed in the future. One of our more immediate goals is to improve the public documentation for DKAN, so we'll try to make sure this is addressed there in the short term.

**Comment by ajacinto** [comment] 2016-12-12 08:53
@jvitello 

Thanks or the replies. I'm currently using DKAN (dkan-7.x-1.12.11) with Acquia. I tried what you suggested applying the formatting on the Y-axis and it produced the same results. 

![thousands-format](https://cloud.githubusercontent.com/assets/716642/21093093/f4f7e266-c08a-11e6-810a-2f1203971f9d.jpg)

For the pie charts, we were hoping to display the breakdown of the figures that was already in the data instead of a calculated percentage that was being returned by DKAN. Since the respective amounts were already included per slice, wouldn't it be possible to just have a checkbox that allowed users to return the actual value instead of the calculated percentage for a bit more control?

**Comment by jvitello** [comment] 2016-12-13 19:24
@ajacinto Can you link to the data? I'll give it a test and see if I can reproduce the issue.

re: Pie Charts: I'll add notes in the feature request, but it's really difficult to determine when it might be picked up for implementation. If you can find a developer, make a fix and submit a PR!

**Comment by ajacinto** [comment] 2016-12-14 07:49
@jvitello - Thanks! Here's a link to the data. Looking forward to your feedback. 
http://adbdkan2kbpjq5ofre.devcloud.acquia-sites.com/sites/default/files/dkan-statistics_7.csv

Noted on the pie chart comments. For now, we just made changes to the default values of the nvd3 library. It's not much of a fix, but it works for now.

**Comment by jvitello** [comment] 2016-12-22 01:23
I was able to recreate the formatting issue on 1.12.11. There seems to be some inconsistency on the development branch. We have a ticket in the queue. It will likely be fixed as part of DKAN 1.13, but I'm not sure if it will be fixed as a minor release to 1.12.x.

**Comment by ajacinto** [comment] 2017-02-14 01:20
This appears partially fixed in 1.12. On mouseover, the y-value reflects the number format selected, but the shown value for the bar is unaffected. I've attached a screenshot for reference. 
![chart-decimal-issue](https://cloud.githubusercontent.com/assets/716642/22910705/bd680cfc-f296-11e6-955e-41965164e884.png)

**Comment by stefaniefgray** [comment] 2017-11-02 17:54
This issue is still happening -- see https://github.com/GetDKAN/dkan/issues/2181

**Comment by Katsivelisp** [comment] 2017-11-07 11:13
Hi,

I've been dealing with issue on 1.13 as well. A discrete bar chart displays numbers instead of regular labels, even though I have selected the X-axis format to be "String" and later on "Text". 

Just to add though that this is an issue with Chrome. Firefox seems to display labels just fine. Can you reproduce this?

**Comment by kimwdavidson** [comment] 2017-11-10 21:21
This ticket is a duplicate of another one in our backlog. We'll close this one and track this issue in #2181.

**Closed by kimwdavidson** 2017-11-10 21:21 UTC
Labels: bug, Component: Visualization, ready for estimation
