### ISSUE TITLE
Implementing a DCO for DKAN

### ISSUE THREAD

**Issue by nerdstein** [GetDKAN/dkan#2165] opened 2017-10-04 15:44 UTC
1. We need developers to add a signoff flag in the commit and have a bot that checks each commit has been signed off. Bot examples: 
- https://github.com/alexellis/derek
- https://github.com/wking/signed-off-by

The "signed off by" might be a better one to use because it seems to be more specific to what we want.

2. DCO text is in the contributors file. The sign off would be acknowledging the DCO. DCO baseline: https://elinux.org/Developer_Certificate_Of_Origin -- @marctjones can create one for DKAN

3. The DCO should be a link from the readme file. 

4. @marctjones drafts an email to introduce CivicActions as product maintainers, describes licensing approach, and confirms use of license from existing contributions. Ask or confirm employment if contributions were paid. @marctjones to send to all 39 contributors.

**Comment by acouch** [comment] 2018-06-27 16:23
Duplicate of https://github.com/GetDKAN/dkan/issues/2165

**Closed by acouch** 2018-06-27 16:23 UTC
Labels: Icebox, Legal
