### ISSUE TITLE
Graph preview does not plot datetime columns

### ISSUE THREAD

**Issue by tryggvit** [GetDKAN/dkan#2769] opened 2018-12-07 18:48 UTC
Dataset "graph" preview of CSV-file does not handle timestamp fields, see attached image.

## Steps to Reproduce

1. Create a new data resource and upload CSV-file of the form:
TIME,T
2018-12-01 00:00:00,0.9
2018-12-02 00:00:00,-0.5
2018-12-03 00:00:00,0.4
2018-12-04 00:00:00,2.4

2. Check "Graph" in Data Previews
3. Save
4. Select "Graph" preview, TIME as Group column and T as Series A
5. Expected behaviour is to show the timeseries by days, but the data is all ploted on single "2018" point.

![screenshot from 2018-12-07 18-28-45](https://user-images.githubusercontent.com/6797699/49666506-38ad2880-fa50-11e8-99c3-333cbc6c7180.png)

It seems the "TIME" column is interpreted as a string, see the "Fields" tab. I have tried every format of timestamp I can think of, with the same results.

**Comment by dafeder** [comment] 2019-01-08 16:45
@janette can you find the related issues and link them to this? Maybe we can make a small epic and try to fix these together.

**Comment by kimwdavidson** [comment] 2019-04-03 20:15
@stefaniefgray: could you link all the recline/preview/date issues here?

**Comment by stefaniefgray** [comment] 2019-04-11 23:25
This ticket, regarding graph previews, has to do with the Recline module. However, our date issues may go beyond this and may be tied to the datastore.

Here is the original issue from California waterboards regarding how DKAN handles dates: https://github.com/NuCivic/cadepttech/issues/88

Original issue about how the Visualizations entity has trouble with dates:
https://github.com/GetDKAN/dkan/issues/1530

More recent issue about how the Visualizations entity has trouble with dates:
https://github.com/GetDKAN/dkan/issues/2181
^ This ticket was in the backlog for a long time but closed during summer 2018 for not being on the roadmap.

Finally, here's a document where I QA'd all of the various issues with DKAN dates and how they're encoded: https://docs.google.com/document/d/1-inwpN14Rr730C9ldJsAUA1SwFjlyI88wfwebv6m6I8/edit#

The issue has something to do with UTF-8 encoding and how it interacts with ISO-8601 encoding. UTF-8 needs to be able to detect the encoding of CSV date strings

From StackOverflow: UTF-8 dates not encoding properly with PHP - https://stackoverflow.com/questions/24895635/utf-8-dates-doesnt-encode-properly

**Comment by erogray** [comment] 2019-05-28 17:47
http://stefanie.dkandemo.nuamsdev.com/dataset/gold-prices-london-1950-2008-monthly may provide good test fixture

**Comment by kimwdavidson** [comment] 2019-06-03 16:52
@janette to also check how the related tickets might be fixed by this fix

**Comment by dharizza** [comment] 2019-06-10 17:53
The issue seems to be in https://github.com/GetDKAN/recline/blob/7.x-2.x/recline.js#L371 because when we have the X axis being a date formatted value, the X is coming as a value parsed to numbers, for example 2018.5 or something similar, in this case there is no index in the models array that can pick that up, triggering the code in the catch which just returns the numeric value which then is weird. The graph per se is not bad, the issue is with the function domain and the labels of the X axis in these cases.

Putting this on hold to reconsider if fixing this worths the time as we are moving to dkan2 and other types of visualization and this seems to never have worked correctly.

**Comment by jensr** [comment] 2019-06-19 11:02
Just an observation: We've been aware of this issue for a while.  We have worked around it by adding an additional column to data sets to express time in a numerical format - e.g. Days since a given date, or a decimal year expression of the date in question. This allow us to create the graphing for those datasets, but obviously does add an extra column to a dataset (which can be quite handy even if users are downloading the dataset as well)

**Comment by dafeder** [comment] 2024-12-16 17:34
Closing as support for DKAN 1.x has ended

**Closed by dafeder** 2024-12-16 17:34 UTC
Labels: Component: Recline, bug
