### ISSUE TITLE
URL Is invalid: File Upload

### ISSUE THREAD

**Issue by kevindavis338** [GetDKAN/dkan#2086] opened 2017-09-01 20:22 UTC
Hi there,

When I try to upload a file, I get the following message: 

The Url Is invalid.

When I check the log I see the following message:

Notice: Undefined index: filefield_dkan_remotefile in dkan_dataset_resource_node_form_validate() (line 536 of /dkan/dkan/profiles/dkan/modules/dkan/dkan_dataset/dkan_dataset.forms.inc).

It happens when I work on a resource. It doesn't happen elsewhere.

Thank you,
Kevin Davis

**Comment by dkinzer** [comment] 2017-09-01 20:56
@kevindavis338 what version of dkan are you noticing this issue in.

**Comment by dkinzer** [comment] 2017-09-01 21:01
Also, what's the URL you are using.  Is it valid?  By any chance are you adding a space at the end?  Spaces at the end of a URL can cause it to be invalid.

**Comment by kevindavis338** [comment] 2017-09-01 21:14
I'm using DKAN version .136 and for the url is this:

http://url/?q=dataset/datasetname/resource/df6f6668-8bb9-4521-804c-bd38173479bf 

and when I edit the resource the url changes to this: http://url/?q=node/1418/edit

No space.

**Comment by dkinzer** [comment] 2017-09-01 21:23
@kevindavis338 that URL is not valid because it does not contain a hostname.

For reference, here is a link to the validation function we use to validate these URLs: https://api.drupal.org/api/drupal/includes%21common.inc/function/valid_url/7.x

**Comment by kevindavis338** [comment] 2017-09-01 21:28
Really, I've done it on a dev site with a similar url and worked before.

**Comment by dkinzer** [comment] 2017-09-01 21:41
hmm...  I guess you are right I tried it locally and it does load broken file because that url doesn't go anywhere.

I can make it throw en error only if i add a space at the end of the file though ```root@cli:/var/www/docroot# drush eval 'var_dump(valid_url("http://url/?q=dataset/datasetname/resource/df6f6668-8bb9-4521-804c-bd38173479bf"));'
bool(true)
root@cli:/var/www/docroot# drush eval 'var_dump(valid_url("http://url/?q=dataset/datasetname/resource/df6f6668-8bb9-4521-804c-bd38173479bf "));'
bool(false)
```

**Comment by dkinzer** [comment] 2017-09-01 21:52
@kevindavis338 my guess is that on your dev environment you have a hostname file that defines `url` so that is why it works.

**Comment by kevindavis338** [comment] 2017-09-01 21:55
Ok, I'll talk to the admin on Tuesday and I'll get back to you..

**Comment by kevindavis338** [comment] 2017-09-06 14:59
Ok, I spoke to the admin, and the url (fwiw, it is sample-host not the actual name), and checked the file and no space at the end.  Still getting the issue.

**Comment by dkinzer** [comment] 2017-09-06 15:04
@kevindavis338 the issue would be with the input of the URL in the field not the file name in the computer.  Make sure also that the input does not contain any extraneous characters at the beginning.

**Comment by kevindavis338** [comment] 2017-09-06 15:44
So what you are saying that the following url: http://hostname/?q=dataset/dataset-name/resource/df6f6668-8bb9-4521-804c-bd38173479bf is invalid.

**Comment by kevindavis338** [comment] 2017-09-07 13:38
Also, the dev environment has version 7.x-1.13.3 while the prod has 7.x-1.13.7

**Comment by dkinzer** [comment] 2017-09-07 14:23
No, all I'm saying is that I can't reproduce the issue with that URL when I try it as you post it.

**Comment by kevindavis338** [comment] 2017-09-07 15:12
Ok, I updated the dev from 7.x-1.13.3 to 7.x-1.13.7 and now I'm getting same issue: Undefined index: filefield_dkan_remotefile in dkan_dataset_resource_node_form_validate() (line 536 of /var/www/html/dkan/profiles/dkan/modules/dkan/dkan_dataset/dkan_dataset.forms.inc)

**Comment by kevindavis338** [comment] 2017-09-20 20:28
Update:

Here is what I did.. I edited the resources on dev and prod and here is what happened:

http://dev/?q=dataset/dataset/resource/d7ea7d3c-3cb8-4306-903b-c024557c7148 < Save file with resource but no preview of the file
http://prod/?q=dataset/dataset/resource/d7ea7d3c-3cb8-4306-903b-c024557c7148 < won't save resource

My question is could a module cause interference?

**Comment by janette** [comment] 2017-10-25 22:18
@kevindavis338 can you upload other files to your resource? or is it specific to a specific file?
a) unable to save any resource file on prod > check permissions on the default/files directory
b) only an issue for a specific file > what is the size of the file, what format is the file, what is the encoding of the file

**Comment by acouch** [comment] 2018-06-27 15:03
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.

**Closed by acouch** 2018-06-27 15:03 UTC
Labels: Needs spec
