### ISSUE TITLE
Aggregation for datastore queries 

### ISSUE THREAD

**Issue by ghost** [GetDKAN/dkan#3459] opened 2021-05-06 18:43 UTC
Add aggregation options to the query endpoint to allow:
*General payments by recipient type across all years
*General payments by recipient type & nature across all years
*Research payments by recipient type across all years
*Ownership payments by recipient type across all years

**Comment by susisiman** [comment] 2021-07-23 14:05
Duplicate of #3480

**Closed as completed by susisiman** 2021-07-23 14:05 UTC
