### ISSUE TITLE
Undefined offset error message when clicking around while running a harvest

### ISSUE THREAD

**Issue by dharizza** [GetDKAN/dkan#2909] opened 2019-06-26 00:46 UTC
Undefined offset error message when clicking around while a harvest is run.
![image](https://user-images.githubusercontent.com/2200763/60142943-49698580-9779-11e9-828d-3b15555f4db1.png)

We might need an override in nuboot_radix for Implements theme_status_messages().

This appeared after https://github.com/GetDKAN/dkan/pull/2903

**Comment by erogray** [comment] 2019-07-09 17:56
Closing since it's hard to reproduce; can reopen if it happens again.

**Closed by erogray** 2019-07-09 17:56 UTC
