### ISSUE TITLE
"View Published" button should not be shown if it cannot be used

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2915] opened 2019-07-03 18:05 UTC
**Problem:**
On workflow sites where a user does not have permissions to view Revisions, or where an asset does not have Revisions, the "View Published" button still appears, but leads nowhere.

**Example:**
![Screenshot 2019-06-28 18 34 04](https://user-images.githubusercontent.com/9059428/60377720-6353d400-99d6-11e9-82d1-ec1a9123dade.png)

**User story:**
As a user viewing a dataset with no revisions (or where I do not have permissions to view Revisions), I should NOT be able to see the "View Published" button that leads to nowhere.

**Acceptance criteria**
- The "View Published" button does not display if the "Revisions" button is not displayed -- whether due to lack of revisions, or the user lacking permission to view them.
- The functionality in the "Expected Behavior" section (see above) works the same regardless, whether or not Workflow is enabled.

See also https://github.com/GetDKAN/dkan/issues/2147 and https://github.com/GetDKAN/dkan/pull/2174

Example URL: 
https://data.louisvilleky.gov/dataset/dockless-vehicles

**Comment by dharizza** [comment] 2019-08-21 21:50
The "View published" button is the expected behavior provided by workbench_moderation, the buttons are not really buttons, they are tabs which let you browser between different pages related to the current node, so the "View published" is in blue because that's the current page (it is a highlighted tab) so the other tabs that may appear (for example the "Add feedback" one) will redirect the user to other pages. Removing the button completely just based on permissions doesn't seem like the right thing as it will prevent user going back to the node page if they are in one of the other tab pages.
Closing as it is working as intended.

**Closed by dharizza** 2019-08-21 21:50 UTC

**Comment by janette** [comment] 2019-08-21 21:56
@dharizza we want to avoid displaying the tab if no other tabs are present, as it serves no purpose if there are no revisions to that node.
