### ISSUE TITLE
Malwares found in DKAN files

### ISSUE THREAD

**Issue by odvietnam** [GetDKAN/dkan#2011] opened 2017-07-18 04:26 UTC
Our server admin reported that they found malwares in profiles/dkan/modules/contrib/color_field/color_field.drush.inc AND profiles/dkan/test/phpunit/dkan_migrate_base/DKANMigrateBaseTest.php 

Can you please check these files? Thank you.

**Comment by kimwdavidson** [comment] 2017-10-16 21:12
Hi @odvietnam! We're pretty sure these are false positives, but could you post the details of the finding, such as the full report or the message and line number, so we can figure out what the issue is?

Thanks!
Kim

**Comment by Pythagory** [comment] 2017-11-15 17:59
Color Field issue is a false positive, issue was identified and resolved here: https://www.drupal.org/project/color_field/issues/2521920

**Comment by acouch** [comment] 2018-06-27 15:45
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.

**Closed by acouch** 2018-06-27 15:45 UTC
Labels: help wanted
