### ISSUE TITLE
Problem with spaces in file name and non-english characters

### ISSUE THREAD

**Issue by chrodos** [GetDKAN/dkan#2741] opened 2018-11-09 11:14 UTC
Hello,

I have identified an issue when uploading a file with empty spaces or non-engish characters. The file uploads but it cannot be downloaded. 

DKAN version 1.15.4

Try this file: http://opendata-sandbox.ouc.ac.cy/dataset/%CE%BC%CE%AD%CF%83%CE%B5%CF%82-%CE%B4%CE%B1%CF%80%CE%AC%CE%BD%CE%B5%CF%82-%CF%84%CE%BF%CF%85%CF%81%CE%B9%CF%83%CF%84%CF%8E%CE%BD-%CE%BA%CE%B1%CF%84%CE%AC-%CE%BC%CE%AE%CE%BD%CE%B1/resource/c81bed08-2cbe-445c-97b8-8da428884359

This is what we get:
![image](https://user-images.githubusercontent.com/5204324/48259655-52dbf280-e421-11e8-84b3-75a118d38108.png)

**Comment by stefaniefgray** [comment] 2018-11-09 15:17
Hi Christos,

I've used one of our demo sites to create a sample Greek CSV data resource in order to reproduce this error. Here's my sample file - Google Translate has been quite helpful:

http://andrew.dkandemo.nuamsdev.com/dataset/%CF%83%CF%85%CE%BD%CE%BF%CE%BB%CE%B9%CE%BA%CE%AC-%CF%86%CF%81%CE%BF%CF%8D%CF%84%CE%B1/resource/a9fd8d54-86f9-4418-b9ed-af59e351b120#{view-graph:{graphOptions:{hooks:{processOffset:{},bindEvents:{}}}},graphOptions:{hooks:{processOffset:{},bindEvents:{}}}}

After uploading this file to DKAN and importing it to the Datastore, I haven't been able to reproduce any errors by using a file with non-English characters in the CSV and in the file name itself -- and even with a space!

However, looking back at your file, it seems the lengthy filename has both a "%20" and spaces. This is problematic, because "%20" is used to represent spaces in a hexadecimal format where they otherwise cannot be encoded.

It appears that DKAN is confused by the combination of "%20" _and_ spaces within a single URL, and therefore, may not know how to read or encode it.

I would recommend renaming the file to something short and sweet, and getting rid of all instances of "%20."

Hope this helps! Let me know if there’s anything else you need, and I’ll be happy to help.

-Stefanie Gray, DKAN Support

**Comment by chrodos** [comment] 2018-11-13 09:29
@stefaniefgray The file name is without the %20. Most of these files were pre-existing. This comes from an upgrade. The problem is that not all files have this problem. I will delete this upgrade and try to upgrade to 1.5.15.

**Comment by stefaniefgray** [comment] 2018-11-13 17:47
@Chrodos Thanks for letting us know - please keep us posted!

**Comment by stefaniefgray** [comment] 2018-11-19 21:49
Hi Chrodos,

The file appears to be working now! I visited http://opendata-sandbox.ouc.ac.cy/dataset/%CE%BC%CE%AD%CF%83%CE%B5%CF%82-%CE%B4%CE%B1%CF%80%CE%AC%CE%BD%CE%B5%CF%82-%CF%84%CE%BF%CF%85%CF%81%CE%B9%CF%83%CF%84%CF%8E%CE%BD-%CE%BA%CE%B1%CF%84%CE%AC-%CE%BC%CE%AE%CE%BD%CE%B1/resource/c81bed08-2cbe-445c-97b8-8da428884359, and the preview looks perfectly fine.

Did the upgrade fix your issue? Please let us know!

Best regards,
Stefanie Gray

**Comment by stefaniefgray** [comment] 2018-11-22 17:54
@chrodos Hi Christos! Today is a U.S. holiday (Thanksgiving) and our team won't be back until Monday - however, we'll continue to look into this issue. Have a good day!

**Comment by dafeder** [comment] 2018-12-06 16:48
@chrodos - what version was this working on?

**Comment by chrodos** [comment] 2018-12-07 11:51
@stefaniefgray and @dafeder I Just updated it to the latest version and it seems to work. I will do some more tests and let you know.

**Comment by dafeder** [comment] 2018-12-07 12:31
Thanks @chrodos - closing this issue for now in that case, please feel free to re-open if you encounter more issues.

**Closed by dafeder** 2018-12-07 12:31 UTC
Labels: Conversations, bug
