### ISSUE TITLE
'view' button mislabeled and revisions hidden when workflow enabled

### ISSUE THREAD

**Issue by jvitello** [GetDKAN/dkan#2147] opened 2017-09-27 20:43 UTC
## Description

When viewing the site as an anonymous user, the 'View' and 'Revisions' buttons on content pages are not displaying as expected when workflow is enabled.

### Scenario: no revisions exist

Given a content node *does not* have any saved revisions

When I view the content page as an anonymous user
Then I should *not* see buttons for 'View' or 'Revisions'

### Scenario: revisions exist
Given a content node *does* have saved revisions

When I view the content page as an anonymous user
Then I *should* see buttons for 'View' and 'Revisions'
And 'View' should be highlighted

When I view the revisions page as an anonymous user
Then I should see buttons for 'View' and 'Revisions'
And 'Revisions' should be highlighted

![screen shot 2017-02-07 at 11 59 17 am](https://user-images.githubusercontent.com/5174815/30936716-b8482500-a3a2-11e7-8564-ad3323730c00.png)

## Current Behavior when DKAN Workflow is enabled

When viewing a dataset as an anonymous user there is a button on content pages 'view published' that links directly back to the page itself. Customers are finding this confusing, because it does nothing but link back to the page already being viewed and there are no other selections available.

![screen shot 2017-02-07 at 11 33 47 am](https://user-images.githubusercontent.com/5174815/30936733-c4da613e-a3a2-11e7-8b86-9f1e795b9e6d.png)

## Steps to Reproduce

- Enable DKAN workflow
- Find a dataset with revisions, or add one
- Log out and view as an anonymous user

## Acceptance criteria

* The functionality in the *Expected Behavior* section works the same when workflow is either enabled or disabled

**Comment by jvitello** [comment] 2017-09-27 20:44
We'd like to see if there are any other solutions from the community available, since this should be a universal issue with workflow. If there aren't any solutions already available, we should see if we can recreate the revisions pages that are available when workflow is disabled when workflow is enabled. This would mean adding the 'Revisions' tab and linking it to /node/#/revisions like it works when workflow is disabled.

**Comment by erogray** [comment] 2017-10-09 22:37
This appears to be an issue currently affecting California. It'd be good to get this worked on.

**Comment by janette** [comment] 2017-10-10 21:33
Patch for this issue https://www.drupal.org/node/1512442
This fixes the visibility problem for anonymous users but the button is labeled 'Moderate' rather than 'Revisions' so we should check the user variable and if anon, change the label on the button to 'Revisions' so it is clear anonymous users can not moderate content.

- [ ] Add patch to drupal-org.make https://www.drupal.org/files/issues/1512442-20-workbench_moderation-fix_access_check.patch
- [ ] Add check for user type and change the button text if user is anonymous

**Comment by stefaniefgray** [comment] 2019-06-29 00:58
Re-opening this issue because it was pointed out by Michael Schneurle of https://data.louisvilleky.gov/

See what @jvitello wrote above in the section "Current Behavior when DKAN Workflow is enabled:"

This is the exact behavior that is still happening on sites with Workflow where the Revisions button has been disabled for certain viewers (i.e. anonymous users.)

**Example currently happening on Louisville and other Workflow sites:**
![Screenshot 2019-06-28 18 34 04](https://user-images.githubusercontent.com/9059428/60377720-6353d400-99d6-11e9-82d1-ec1a9123dade.png)

**Summary:**
As a user viewing a dataset with no revisions (or where I do not have permissions to view Revisions), I should NOT be able to see the "View Published" button that leads to nowhere.

**Acceptance criteria**
- The "View Published" button does not display if the "Revisions" button is not displayed -- whether due to lack of revisions, or the user lacking permission to view them.
- The functionality in the "Expected Behavior" section (see above) works the same regardless, whether or not Workflow is enabled.

**Comment by erogray** [comment] 2019-07-03 18:05
Re-closing in favor of https://github.com/GetDKAN/dkan/issues/2915

**Closed by erogray** 2019-07-03 18:05 UTC
Labels: Component: Workflow, bug
